2024-12-16 00:06:27,973 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:07:33,421 - INFO - Скопирована директория: X:\Криминальное чтиво -> C:/Yarik/testBAckup/Новая папка\Криминальное чтиво
2024-12-16 00:19:31,636 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:20:18,136 - INFO - Создана новая директория: C:/Yarik/testBAckup/Новая папка
2024-12-16 00:20:18,137 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:32:06,591 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:32:06,591 - ERROR - Ошибка при копировании Снимок экрана 2024-12-16 003054.png: [WinError 183] Невозможно создать файл, так как он уже существует: 'C:/Yarik/testBAckup/test4'
Traceback (most recent call last):
  File "c:\Yarik\Kursovaya2\FlashBackup\TkForge\main.py", line 128, in copy_files_from_flash_drive
    shutil.copytree(flash_drive_path, destination_folder)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LyollyaUser\AppData\Local\Programs\Python\Python313\Lib\shutil.py", line 593, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
                     ignore=ignore, copy_function=copy_function,
                     ignore_dangling_symlinks=ignore_dangling_symlinks,
                     dirs_exist_ok=dirs_exist_ok)
  File "C:\Users\LyollyaUser\AppData\Local\Programs\Python\Python313\Lib\shutil.py", line 491, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 227, in makedirs
FileExistsError: [WinError 183] Невозможно создать файл, так как он уже существует: 'C:/Yarik/testBAckup/test4'
2024-12-16 00:32:16,771 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:32:16,771 - ERROR - Ошибка при копировании Снимок экрана 2024-12-16 003054.png: [WinError 183] Невозможно создать файл, так как он уже существует: 'C:/Yarik/testBAckup/test4'
Traceback (most recent call last):
  File "c:\Yarik\Kursovaya2\FlashBackup\TkForge\main.py", line 128, in copy_files_from_flash_drive
    shutil.copytree(flash_drive_path, destination_folder)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LyollyaUser\AppData\Local\Programs\Python\Python313\Lib\shutil.py", line 593, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
                     ignore=ignore, copy_function=copy_function,
                     ignore_dangling_symlinks=ignore_dangling_symlinks,
                     dirs_exist_ok=dirs_exist_ok)
  File "C:\Users\LyollyaUser\AppData\Local\Programs\Python\Python313\Lib\shutil.py", line 491, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 227, in makedirs
FileExistsError: [WinError 183] Невозможно создать файл, так как он уже существует: 'C:/Yarik/testBAckup/test4'
2024-12-16 00:33:22,153 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:33:22,154 - ERROR - Ошибка при копировании Снимок экрана 2024-12-16 003054.png: [WinError 3] Системе не удается найти указанный путь
Traceback (most recent call last):
  File "c:\Yarik\Kursovaya2\FlashBackup\TkForge\main.py", line 128, in copy_files_from_flash_drive
    shutil.copy2(flash_drive_path, destination_folder)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LyollyaUser\AppData\Local\Programs\Python\Python313\Lib\shutil.py", line 453, in copy2
    _winapi.CopyFile2(src_, dst_, flags)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь
2024-12-16 00:33:38,183 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:33:38,184 - ERROR - Ошибка при копировании Снимок экрана 2024-12-16 003054.png: [WinError 3] Системе не удается найти указанный путь
Traceback (most recent call last):
  File "c:\Yarik\Kursovaya2\FlashBackup\TkForge\main.py", line 128, in copy_files_from_flash_drive
    shutil.copy2(flash_drive_path, destination_folder)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LyollyaUser\AppData\Local\Programs\Python\Python313\Lib\shutil.py", line 453, in copy2
    _winapi.CopyFile2(src_, dst_, flags)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь
2024-12-16 00:34:54,993 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:34:54,995 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 00:36:27,932 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:36:27,933 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 00:37:27,644 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:37:27,646 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 194747.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 194747.png
2024-12-16 00:37:27,648 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195147.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195147.png
2024-12-16 00:37:27,649 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 00:37:27,650 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195419.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195419.png
2024-12-16 00:37:27,652 - INFO - Копирован файл: X:\Снимок экрана 2024-10-02 003637.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-02 003637.png
2024-12-16 00:37:27,652 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 00:37:45,388 - INFO - Скопирована директория: X:\1234 -> C:/Yarik/testBAckup/test4\1234
2024-12-16 00:37:45,388 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:37:45,389 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 00:37:45,390 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 00:38:05,056 - INFO - Скопирована директория: X:\1234 -> C:/Yarik/testBAckup/test4\1234
2024-12-16 00:38:05,057 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:38:05,058 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 00:38:05,059 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 00:38:55,120 - INFO - Скопирована директория: X:\1234 -> C:/Yarik/testBAckup/test4\1234
2024-12-16 00:38:55,120 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:38:55,121 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 00:38:55,122 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 00:45:34,414 - WARNING - Путь к флешке или папке назначения не указан.
2024-12-16 00:45:50,006 - ERROR - Ошибка при копировании 1234: [WinError 183] Невозможно создать файл, так как он уже существует: 'C:/Yarik/testBAckup/test4\\1234'
Traceback (most recent call last):
  File "c:\Yarik\Kursovaya2\FlashBackup\TkForge\main.py", line 131, in copy_files_from_flash_drive
    shutil.copytree(source_path, destination_path)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LyollyaUser\AppData\Local\Programs\Python\Python313\Lib\shutil.py", line 593, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
                     ignore=ignore, copy_function=copy_function,
                     ignore_dangling_symlinks=ignore_dangling_symlinks,
                     dirs_exist_ok=dirs_exist_ok)
  File "C:\Users\LyollyaUser\AppData\Local\Programs\Python\Python313\Lib\shutil.py", line 491, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 227, in makedirs
FileExistsError: [WinError 183] Невозможно создать файл, так как он уже существует: 'C:/Yarik/testBAckup/test4\\1234'
2024-12-16 00:45:51,514 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:45:51,516 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 00:45:51,517 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 00:46:21,644 - INFO - Скопирована директория: X:\1234 -> C:/Yarik/testBAckup/test4\1234
2024-12-16 00:46:21,644 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:46:21,645 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 00:46:21,646 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 00:51:28,981 - INFO - Скопирована директория: X:\1234 -> C:/Yarik/testBAckup/test4\1234
2024-12-16 00:51:28,981 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:51:28,982 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 00:51:28,983 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 00:53:17,627 - INFO - Скопирована директория: X:\1234 -> C:/Yarik/testBAckup/test4\1234
2024-12-16 00:53:17,628 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:53:17,628 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 00:53:17,630 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 00:58:46,002 - INFO - Скопирована директория: X:\1234 -> C:/Yarik/testBAckup/test4\1234
2024-12-16 00:58:46,002 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 00:58:46,004 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 00:58:46,006 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 01:02:16,668 - INFO - Скопирована директория: X:\1234 -> C:/Yarik/testBAckup/test4\1234
2024-12-16 01:02:16,669 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 01:02:16,670 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 01:02:16,672 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 01:03:36,693 - INFO - Скопирована директория: X:\1234 -> C:/Yarik/testBAckup/test4\1234
2024-12-16 01:03:36,694 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 01:03:36,695 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 01:03:36,696 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 01:03:46,689 - ERROR - Ошибка при копировании 1234: [WinError 183] Невозможно создать файл, так как он уже существует: 'C:/Yarik/testBAckup/test4\\1234'
Traceback (most recent call last):
  File "c:\Yarik\Kursovaya2\FlashBackup\TkForge\main.py", line 137, in copy_files_from_flash_drive
    shutil.copytree(source_path, destination_path)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LyollyaUser\AppData\Local\Programs\Python\Python313\Lib\shutil.py", line 593, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
                     ignore=ignore, copy_function=copy_function,
                     ignore_dangling_symlinks=ignore_dangling_symlinks,
                     dirs_exist_ok=dirs_exist_ok)
  File "C:\Users\LyollyaUser\AppData\Local\Programs\Python\Python313\Lib\shutil.py", line 491, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 227, in makedirs
FileExistsError: [WinError 183] Невозможно создать файл, так как он уже существует: 'C:/Yarik/testBAckup/test4\\1234'
2024-12-16 01:03:47,467 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 01:03:47,469 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 01:03:47,470 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 01:04:19,959 - INFO - Скопирована директория: X:\1234 -> C:/Yarik/testBAckup/test4\1234
2024-12-16 01:04:19,960 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 01:04:19,961 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 01:04:19,962 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 01:05:11,419 - INFO - Скопирована директория: X:\1234 -> C:/Yarik/testBAckup/test4\1234
2024-12-16 01:05:11,420 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 01:05:11,421 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 01:05:11,422 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 01:13:25,971 - INFO - Скопирована директория: X:\1234 -> C:/Yarik/testBAckup/test4\1234
2024-12-16 01:13:25,972 - ERROR - Ошибка при копировании 1234: cannot access local variable 'copied_bytes' where it is not associated with a value
Traceback (most recent call last):
  File "c:\Yarik\Kursovaya2\FlashBackup\TkForge\main.py", line 145, in copy_files_from_flash_drive
    copied_bytes += os.path.getsize(source_path)
    ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'copied_bytes' where it is not associated with a value
2024-12-16 01:13:29,773 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 01:13:29,776 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 01:13:29,776 - ERROR - Ошибка при копировании Снимок экрана 2024-10-01 195400.png: cannot access local variable 'copied_bytes' where it is not associated with a value
Traceback (most recent call last):
  File "c:\Yarik\Kursovaya2\FlashBackup\TkForge\main.py", line 145, in copy_files_from_flash_drive
    copied_bytes += os.path.getsize(source_path)
    ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'copied_bytes' where it is not associated with a value
2024-12-16 01:13:32,786 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 01:13:32,786 - ERROR - Ошибка при копировании Снимок экрана 2024-12-16 003054.png: cannot access local variable 'copied_bytes' where it is not associated with a value
Traceback (most recent call last):
  File "c:\Yarik\Kursovaya2\FlashBackup\TkForge\main.py", line 145, in copy_files_from_flash_drive
    copied_bytes += os.path.getsize(source_path)
    ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'copied_bytes' where it is not associated with a value
2024-12-16 01:34:11,068 - INFO - Скопирована директория: X:\1234 -> C:/Yarik/testBAckup/test4\1234
2024-12-16 01:34:11,069 - ERROR - Ошибка при копировании 1234: update_progress_bar() missing 1 required positional argument: 'copied_bytes'
Traceback (most recent call last):
  File "c:\Yarik\Kursovaya2\FlashBackup\TkForge\main.py", line 145, in copy_files_from_flash_drive
    update_progress_bar()
    ~~~~~~~~~~~~~~~~~~~^^
TypeError: update_progress_bar() missing 1 required positional argument: 'copied_bytes'
2024-12-16 01:34:12,320 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 01:34:12,322 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 01:34:12,322 - ERROR - Ошибка при копировании Снимок экрана 2024-10-01 195400.png: update_progress_bar() missing 1 required positional argument: 'copied_bytes'
Traceback (most recent call last):
  File "c:\Yarik\Kursovaya2\FlashBackup\TkForge\main.py", line 145, in copy_files_from_flash_drive
    update_progress_bar()
    ~~~~~~~~~~~~~~~~~~~^^
TypeError: update_progress_bar() missing 1 required positional argument: 'copied_bytes'
2024-12-16 01:34:13,383 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 01:34:13,383 - ERROR - Ошибка при копировании Снимок экрана 2024-12-16 003054.png: update_progress_bar() missing 1 required positional argument: 'copied_bytes'
Traceback (most recent call last):
  File "c:\Yarik\Kursovaya2\FlashBackup\TkForge\main.py", line 145, in copy_files_from_flash_drive
    update_progress_bar()
    ~~~~~~~~~~~~~~~~~~~^^
TypeError: update_progress_bar() missing 1 required positional argument: 'copied_bytes'
2024-12-16 01:34:59,452 - INFO - Скопирована директория: X:\1234 -> C:/Yarik/testBAckup/test4\1234
2024-12-16 01:34:59,453 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 01:34:59,454 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 01:34:59,456 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 01:38:51,657 - INFO - Копирован файл: X:\01 - Good Morning.flac -> C:/Yarik/testBAckup/test4\01 - Good Morning.flac
2024-12-16 01:38:52,520 - INFO - Копирован файл: X:\02 - Get Happy (2024).flac -> C:/Yarik/testBAckup/test4\02 - Get Happy (2024).flac
2024-12-16 01:38:53,338 - INFO - Копирован файл: X:\03 - Oh, When The Saints.flac -> C:/Yarik/testBAckup/test4\03 - Oh, When The Saints.flac
2024-12-16 01:38:54,131 - INFO - Копирован файл: X:\04 - World On A String.flac -> C:/Yarik/testBAckup/test4\04 - World On A String.flac
2024-12-16 01:38:54,897 - INFO - Копирован файл: X:\05 - If My Friends Could See Me Now.flac -> C:/Yarik/testBAckup/test4\05 - If My Friends Could See Me Now.flac
2024-12-16 01:38:55,948 - INFO - Копирован файл: X:\06 - That's Entertainment.flac -> C:/Yarik/testBAckup/test4\06 - That's Entertainment.flac
2024-12-16 01:38:56,641 - INFO - Копирован файл: X:\07 - Smile.flac -> C:/Yarik/testBAckup/test4\07 - Smile.flac
2024-12-16 01:38:57,421 - INFO - Копирован файл: X:\08 - The Joker.flac -> C:/Yarik/testBAckup/test4\08 - The Joker.flac
2024-12-16 01:38:59,056 - INFO - Копирован файл: X:\10 - Gonna Build A Mountain.flac -> C:/Yarik/testBAckup/test4\10 - Gonna Build A Mountain.flac
2024-12-16 01:38:59,889 - INFO - Копирован файл: X:\11 - Close To You.flac -> C:/Yarik/testBAckup/test4\11 - Close To You.flac
2024-12-16 01:39:00,826 - INFO - Копирован файл: X:\12 - Happy Mistake.flac -> C:/Yarik/testBAckup/test4\12 - Happy Mistake.flac
2024-12-16 01:39:01,051 - INFO - Скопирована директория: X:\1234 -> C:/Yarik/testBAckup/test4\1234
2024-12-16 01:39:01,888 - INFO - Копирован файл: X:\13 - That's Life.flac -> C:/Yarik/testBAckup/test4\13 - That's Life.flac
2024-12-16 01:39:01,944 - INFO - Копирован файл: X:\coverhq.jpg -> C:/Yarik/testBAckup/test4\coverhq.jpg
2024-12-16 01:39:01,945 - INFO - Копирован файл: X:\foo_dr.txt -> C:/Yarik/testBAckup/test4\foo_dr.txt
2024-12-16 01:39:01,946 - INFO - Скопирована директория: X:\Lady Gaga — Harlequin (2024) [FLAC] (24bit-48kHz) [Hi-Res] -> C:/Yarik/testBAckup/test4\Lady Gaga — Harlequin (2024) [FLAC] (24bit-48kHz) [Hi-Res]
2024-12-16 01:39:01,947 - DEBUG - Пропущена системная папка: X:\System Volume Information
2024-12-16 01:39:01,948 - INFO - Копирован файл: X:\[TR24][OF] Lady Gaga - Harlequin - 2024 (Pop) [rutracker-6578141].torrent -> C:/Yarik/testBAckup/test4\[TR24][OF] Lady Gaga - Harlequin - 2024 (Pop) [rutracker-6578141].torrent
2024-12-16 01:39:01,949 - INFO - Копирован файл: X:\Снимок экрана 2024-10-01 195400.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-10-01 195400.png
2024-12-16 01:39:01,950 - INFO - Копирован файл: X:\Снимок экрана 2024-12-16 003054.png -> C:/Yarik/testBAckup/test4\Снимок экрана 2024-12-16 003054.png
2024-12-16 02:10:37,153 - WARNING - Путь к флешке или папке назначения не указан.
